In [15]:
import numpy as np
l1 = [1,4,2,12,13,27,87,34,54,1,3,90,17,12,5,10,55,7,19,20]
arr1 = np.array(l1,dtype=np.int64)
arr2 = arr1.reshape(4,5)
arr2[-1,:] = 0
arr3 = arr2.flatten()
print(arr3)

[ 1  4  2 12 13 27 87 34 54  1  3 90 17 12  5  0  0  0  0  0]


In [8]:
import numpy as np
from random import *
arr = np.array([[randint(10,50) for i in range (5)]for j in range (5)])
print("Array:",arr)
print("Row wise mean:",np.mean(arr,axis=0))
print("Column wise mean:",np.mean(arr,axis=1))
print("Row wise sum:",np.sum(arr,axis=0))
print("Column wise sum:",np.sum(arr,axis=1))
print("Row minimum:",np.min(arr,axis=0))
print("Column minimum:",np.min(arr,axis=1))
print("Row maximum:",np.max(arr,axis=0))
print("Column maximum:",np.max(arr,axis=1))


Array: [[47 24 23 23 26]
 [28 18 27 11 48]
 [35 25 10 49 17]
 [30 17 18 37 23]
 [11 22 44 25 29]]
Row wise mean: [30.2 21.2 24.4 29.  28.6]
Column wise mean: [28.6 26.4 27.2 25.  26.2]
Row wise sum: [151 106 122 145 143]
Column wise sum: [143 132 136 125 131]
Row minimum: [11 17 10 11 17]
Column minimum: [23 11 10 17 11]
Row maximum: [47 25 44 49 48]
Column maximum: [47 48 49 37 44]


In [5]:
import numpy as np
id_matrix = np.eye(4)
id_matrix = 5*np.eye(4)
id_matrix[-1:] = 1
print(id_matrix)

[[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [1. 1. 1. 1.]]


In [30]:
import numpy as np
from random import *
arr = np.array([randint(0,20) for i in range (15)])
print(arr)
unique = np.unique(arr)
print(unique)
print("Count of unique elements :",len(unique))
arr1 = np.where(arr>10)[0]
print(arr1)

[19 16  0 20  0  5 13 18 14 12  2  2 14 17 11]
[ 0  2  5 11 12 13 14 16 17 18 19 20]
Count of unique elements : 12
[ 0  1  3  6  7  8  9 12 13 14]


In [14]:
import numpy as np
from random import *
arr = np.random.uniform(0,1,size=(3,4))
arr = np.round(arr,2)
arr[:,2] = 0.5
print(arr)

[[0.81 0.51 0.5  0.66]
 [0.13 0.26 0.5  0.76]
 [0.59 0.86 0.5  0.13]]
